package:
    type:           yii2-extension
    name:           yii2-pnotify
    title:          Yii2 adapter for PNotify JQuery extension
    headline:       Yii2 PNotify
    keywords:       yii2, pnotify, jquery
    namespace:      hiqdev\pnotify
